# Generated by Django 5.1.2 on 2024-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('categoria', models.CharField(choices=[('Fantasia', 'Fantasia'), ('Matematicas', 'Matematicas'), ('Fisica', 'Fisica')], max_length=255)),
                ('unidades', models.IntegerField(default=0)),
                ('autor', models.ManyToManyField(related_name='autor', to='libreria.autor')),
            ],
        ),
    ]
